# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    #projects: '/src/BFYOCSolutions/BFYOCSolutions.sln'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'OTA-Prod-56(3f415f48-081e-4581-a7ba-993eb30c75c4)'
    appType: 'functionApp'
    appName: 'FunctionAppHack4p'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
